name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build
        run: pip install build

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: endstone_mediaplayer_ui
          path: dist/*.whl
